# config
server_port: 8009
server_host: "0.0.0.0"

opensearch_hosts: "localhost"
opensearch_port: "9200"
opensearch_usr: "admin"
opensearch_pwd: "S202512sss"

static_path: "http://127.0.0.1:8009/"

model_name: "qwen-max"
# glm-4
# deepseek-chat
# qwen-max
# gpt-4o-mini

model_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
# https://open.bigmodel.cn/api/paas/v4/
# https://api.deepseek.com/v1/
# https://dashscope.aliyuncs.com/compatible-mode/v1
# https://api.openai.com/v1
